# Setup
language: zh-CN
title: 热辣漫画资源收集站
tagline: 熱辣漫畫資源站，主要收集熱辣漫畫相關資源
show_downloads: "true"

github:
  web_site: https://www.mrhotmanga.com
  download_site: http://www.hotmangasa.com
  blog_site: https://www.jileshucheng.com

# Build settings
theme: jekyll-theme-cayman
permalink: /404.html

# plugins
plugins:
  - "jekyll-github-metadata"

#Others
markdown: kramdown
